### ISSUE TITLE
Fix directory for cmake files.

### ISSUE THREAD

**Issue by zenker** [ChimeraTK/project-template#12]
Currently the FindPackage file is installed in `/share/cmake-...`:

https://github.com/ChimeraTK/project-template/blob/d86b703f221c7bb6a91bdd72b04df638fa30ca06/cmake/create_cmake_config_files.cmake#L84

But the proper destination is `/usr/share/...`. At least that is where cmake files are installed usually.

**Comment by zenker** [comment]
At least if install prefix is not set by the user. Else it is ok I guess.

**Comment by killenb** [comment]
The destination is share/cmake... relative to the installation prefix (not /share/cmake...)
It seems the default installation prefix is /usr/local for manually installed packages.
The debian packaging scripts set the prefix correctly to /usr so the libraries are in the correct place when installed from a debian package.

**Comment by killenb** [comment]
You should not manually install to places where debian packages are putting their content.

**Comment by zenker** [comment]
Sorry, I set CMAKE_INSTALL_PREFIX empty in one of my tests, accidentally.
